deploy

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -28,13 +28,13 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.tag }}
-      - name: Check if tag exists
-        run: |
-          git fetch --all --tags
-          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
-            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
-            exit 1
-          fi
+#      - name: Check if tag exists
+#        run: |
+#          git fetch --all --tags
+#          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
+#            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
+#            exit 1
+#          fi
       - name: Show cryptoprotos version
         run: |
           cat go.mod
